// let's analyze this topic a little bit more

// Timer(from stdlib) uses extern structure
// To create it, just paste it's fields

stct timespec {
  tv_sec: i64,
  tv_nsec: i64
}
// that's all needed
// and let's import extern fn for timespec also
extern fn timespec_get(ptr, i32): i32

fn main(): i64 {
  let t: timespec
  timespec_get(^t, 1)

  // nanoseconds
  log(t.tv_nsec) // 749281678

  // seconds
  log(t.tv_sec) // 1787400677

  ret 0
}
