/*
    __  __________________                  
   / / / /_  __/_  __/ __ \                 
  / /_/ / / /   / / / /_/ /                 
 / __  / / /   / / / ____/          __      
/_/_/_/_/_/  _/_/ /_/  _____  _____/ /______
  / ___/ _ \/ __ `/ / / / _ \/ ___/ __/ ___/
 / /  /  __/ /_/ / /_/ /  __(__  ) /_(__  ) 
/_/   \___/\__, /\__,_/\___/____/\__/____/  
             /_/                            
Ferra standart library

*/

extern func http_get(str): str
extern func http_post(str, str): str
extern func http_post_h(str, str, str, i64): str
extern func http_free(str)
extern func http_cleanup()
extern func http_stream_open(str, str, str): ptr
extern func http_stream_read(ptr, ptr, usize): i64
extern func http_stream_done(ptr): i32
extern func http_stream_status(ptr): i64
extern func http_stream_error(ptr): str
extern func http_stream_close(ptr)

take "fe/string.fe"

// safer approach of http
stct HttpStream {
  handle: ptr,
  url: str,
  method: str,
  body: str
}
impl HttpStream HttpStream(_u: str, _m: str, _b: str) {
  this.url = _u
  this.method = _m
  this.body = _b
}
impl HttpStream open(): bol {
  this.handle = http_stream_open(this.url, this.method, this.body)

  if this.handle is null { ret false }

  ret true
}
impl HttpStream done(): bol {
  ret http_stream_done(this.handle) is 1
}
impl HttpStream read(buf: i8[], size: usize): i64 {
  ret http_stream_read(this.handle, buf, size)
}
drop HttpStream() {
  http_stream_close(this.handle)
}

stct Http {
  handle: Vec<str> // represents last handled request
}
impl Http Http() {
  this.handle.Vec()
}
impl Http get(url: str): (str, bol) {
  var r: str = http_get(url)

  if r is null {
    ret ("", false)
  }

  this.handle.push(r)

  ret (this.handle[this.handle.size-1], true)
}
impl Http post(url: str, body: str): (str, bol) {
  var r: str = http_post(url, body)

  if r is null {
    ret ("", false)
  }

  this.handle.push(r)

  ret (this.handle[this.handle.size-1], true)
}
impl Http posth(url: str, body: str, headers: str, hsize: i64): (str, bol) {
  var r: str = http_post_h(url, body, headers, hsize)

  if r is null {
    ret ("", false)
  }

  this.handle.push(r)

  ret (this.handle[this.handle.size-1], true)
}
drop Http() {
  for i in this.handle.size {
    free(this.handle[i])
  }

  dropnow this.handle
}
