/*
    __  __________________                  
   / / / /_  __/_  __/ __ \                 
  / /_/ / / /   / / / /_/ /                 
 / __  / / /   / / / ____/          __      
/_/_/_/_/_/  _/_/ /_/  _____  _____/ /______
  / ___/ _ \/ __ `/ / / / _ \/ ___/ __/ ___/
 / /  /  __/ /_/ / /_/ /  __(__  ) /_(__  ) 
/_/   \___/\__, /\__,_/\___/____/\__/____/  
             /_/                            
Ferra standart library

*/

extern func http_get(str): str
extern func http_post(str, str): str
extern func http_post_h(str, str, str, i64): str
extern func http_free(str)
extern func http_cleanup()
extern func http_stream_open(str, str, str): ptr
extern func http_stream_read(ptr, ptr, usize): i64
extern func http_stream_done(ptr): i32
extern func http_stream_status(ptr): i64
extern func http_stream_error(ptr): str
extern func http_stream_close(ptr)

take "fe/string.fe"

// safer approach of http
stct Http {
  handle: str // represents last handled request
}

impl Http get(url: str): (str, bol) {
  dropnow this

  var r: str = http_get(url)

  if r is null {
    ret ("", false)
  }
  this.handle = r
  ret (r, true)
}
impl Http post(url: str, body: str): (str, bol) {
  dropnow this

  var r: str = http_post(url, body)

  if r is null {
    ret ("", false)
  }
  this.handle = r
  ret (r, true)
}
impl Http posth(url: str, body: str, headers: str, h_count: i64): (str, bol) {
  dropnow this

  var r: str = http_post_h(url, body, headers, h_count)

  if r is null {
    ret ("", false)
  }
  this.handle = r
  ret (r, true)
}

drop Http() {
  if this.handle not null {
    http_free(this.handle)
  }
}

const http: Http
