/*
    ____             _       ___           __             
   / __ \____ ___  _| |     / (_)___  ____/ /___ _      __
  / /_/ / __ `/ / / / | /| / / / __ \/ __  / __ \ | /| / /
 / _, _/ /_/ / /_/ /| |/ |/ / / / / / /_/ / /_/ / |/ |/ / 
/_/ |_|\__,_/\__, / |__/|__/_/_/ /_/\__,_/\____/|__/|__/  
  ____  ____/____/                                        
 / __ \/ ___/                                             
/ /_/ / /                                                 
\____/_/              ___ __                 __  ___ __   
   / __ \____ ___  __/ (_) /_     ___  _  __/ /_/ (_) /_  
  / /_/ / __ `/ / / / / / __ \   / _ \| |/_/ __/ / / __ \ 
 / _, _/ /_/ / /_/ / / / /_/ /  /  __/>  </ /_/ / / /_/ / 
/_/ |_|\__,_/\__, /_/_/_.___/   \___/_/|_|\__/_/_/_.___/  
            /____/                                        
Ferra ext library

*/

stct Texture2D {
  id: u32,
  width: i32,
  height: i32,
  mipmaps: i32,
  format: i32
}

stct Rectangle {
  x: f32,
  y: f32,
  width: f32,
  height: f32
}

stct Vector2 {
  x: f32,
  y: f32
}

stct Color {
  r: u8,
  g: u8,
  b: u8,
  a: u8
}

const WHITE: Color = Color{ r: 255, g: 255, b: 255, a: 255 }

extern func InitWindow(i32, i32, str)
extern func WindowShouldClose(): bol
extern func BeginDrawing()
extern func EndDrawing()
extern func CloseWindow()
extern func SetTargetFPS(i32)
extern func GetFrameTime(): f32
extern func GetFPS(): i32
extern func IsKeyDown(i32): bol
extern func IsKeyPressed(i32): bol
extern func IsMouseButtonDown(i32): bol
extern func GetMouseX(): i32
extern func GetMouseY(): i32
extern func SetWindowTitle(str)
extern func GetScreenWidth(): i32
extern func GetScreenHeight(): i32

extern func ClearBackground(Color)
extern func DrawRectangle(i32, i32, i32, i32, Color)
extern func DrawCircle(i32, i32, f32, Color)
extern func DrawPixel(i32, i32, Color)
extern func DrawLine(i32, i32, i32, i32, Color)
extern func DrawText(str, i32, i32, i32, Color)

extern func LoadTexture(ptr): Texture2D
extern func UnloadTexture(Texture2D)
extern func DrawTexture(Texture2D, i32, i32, Color)
extern func DrawTexturePro(Texture2D, Rectangle, Rectangle, Vector2, f32, Color)
