/*
   _____ __       _            
  / ___// /______(_)___  ____ _
  \__ \/ __/ ___/ / __ \/ __ `/
 ___/ / /_/ /  / / / / / /_/ / 
/____/\__/_/  /_/_/ /_/\__, /  
                      /____/   
Ferra standart library

*/

extern func strlen(str): usize
extern func strcmp(str, str): i32
extern func memcpy(ptr, ptr, i64): ptr
extern func strdup(str): str
extern func snprintf(str, i64, str, ...): i32
extern func strncpy(str, str, i64): str
extern func strcpy(str, str): str

extern func isspace(i32): i32
extern func isdigit(i32): i32
extern func isalpha(i32): i32
extern func isalnum(i32): i32

extern func strtof(str, str): f32

take "fe/vec.fe"

stct String {
  data: Vec<i8>
}
impl String String() {
  this.data.Vec()
  this.data.data[0] = 0
}
impl String data(): ptr {
  ret this.data.data
}
impl String push(c: i8) {
  this.data.reserve(this.data.size + 2)
  this.data.push(c)
  this.data.data[this.data.size] = 0
}
impl String pop(): i8 {
  var result: i8 = this.data.pop()
  this.data.data[this.data.size] = 0
  ret result
}
impl String len(): i64 {
  ret this.data.size
}
impl String cstr(): str {
  ret this.data.data as str
}
impl String append(t: str) {
  var n: i64 = strlen(t)
  var old_size: i64 = this.data.size

  this.data.reserve(old_size + n + 1)

  memcpy(
    this.data.data + old_size,
    t,
    n
  )

  this.data.size = old_size + n
  this.data.data[this.data.size] = 0
}
impl String clear() {
  this.data.clear()
  this.data.data[0] = 0
}
impl String reserve(n: i64) {
  this.data.reserve(n)
}
impl String empty(): bol {
  ret this.data.size is 0
}
impl String contains(c: str): bol {
  for i in this.len() {
    if this.data.data[i] is c as i8 { ret true }
  }
  ret false
}
impl String capacity(): i64 {
  ret this.data.capacity
}
impl String set(i: i64, c: i8) {
  this.data.data[i] = c
}
impl String front(): i8 {
  ret this.data.data[0]
}
impl String back(): i8 {
  ret this.data.data[this.data.size-1]
}

impl String starts(c: str): bol {
  if strlen(c) > this.len() { ret false }

  for i in strlen(c) {
    if this.data.data[i] not c[i] { ret false }
  }

  ret true
}
impl String ends(c: str): bol {
  var len_str: i64 = this.len()-1
  var len_suffix: usize = strlen(c)
  
  if len_suffix > len_str { ret false }

  for i in len_suffix {
    if this.data.data[len_str - 1 - i] not c[len_suffix - 1 - i] { ret false }
  }

  ret true
}
impl String split(c: str, out: Vec<str>): bol {
  if this.contains(c) is false { ret false }

  var cur: String()

  for i in this.len() {
    if this.data.data[i] is (c as i8) {
      out.push(strdup(cur.cstr()))
      cur.clear()
    } else {
      cur.append(this.data.data[i] as str)
    }
  }
  out.push(strdup(cur.cstr()))

  ret true
}

oper String <[i: i64]> {
  ret this.data[i]
}

drop String() {
  this.data.unvec()
}
