take "fe/hashmap.fe"

fn main(): i64 {
  let names: HashMap<str, isize, StrPolicy>(StrPolicy{})
  names.insert("a", 1)
  names.insert("b", 2)
  names.insert("c", 3)
  names.insert("d", 4)
  names.insert("e", 5)
  names.insert("f", 6)
  names.insert("g", 7)
  names.insert("h", 8)
  names.insert("i", 9)
  names.insert("j", 10)
  names.insert("k", 11)
  names.insert("l", 12)

  let name_value: isize = 0
  if names.count != 12 or names.find("l", ^name_value) is false or
     name_value != 12 or names["l"]^ != 12 or
     names.capacity != 32 { ret 2 }

  let numbers: HashMap<i64, isize, IPolicy<i64>>(IPolicy<i64>{})
  numbers.insert(1, 40)
  numbers.insert(2, 41)
  numbers.insert(1, 42)

  let found: isize = 0
  let value: isize = 0
  if numbers.find(1, ^value) { found = 1 }

  if found == 1 and value == 42 and numbers.count == 2 { ret 0 }
  ret 1
}
