fn main(): i64 {
  let true_single: f32 = true as f32
  let false_single: f32 = false as f32
  let true_double: f64 = true as f64
  let false_double: f64 = false as f64
  let from_single: bol = 2.5 as bol
  let from_zero: bol = 0.0 as bol

  if true_single == 1.0 and false_single == 0.0 and
     true_double == 1.0 and false_double == 0.0 and
     from_single and not from_zero {
    ret 0
  }
  ret 1
}
